---
# I barely understand any of this

- name: "Playbook 1: Testing Genie"
  hosts: cswitch01
  connection: network_cli

  tasks:
    - name: "Task 1 - send a show command"
      cisco.ios.ios_command:
        commands: "show ip route"
      register: show_ip_route_output

    - name: "Task 2 - Parse show command"
      set_fact:
        parsed_data: >-
          {{ show_ip_route_output.stdout[0] | clay584.genie.parse_genie(
          command='show ip route', os='ios') }}

    - name: "Task 3 - Print Output"
      debug:
        msg: "{{ parsed_data }}"
