----

- name: "Register Playbook"
  hosts: jswitch01
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Push Config"
      junipernetworks.junos.junos_command:
       src: "ntp.j2"
    notify: ntp_handler_example
    register: ntp_result
  
  handlers:
    - name: ntp_handler_example
      debug:
      msg: {{ntp_result}}