---
- name: "Register Playbook"
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: debug ntp variable
      debug:
        var: ntp
    - name: "Push Config for IOS"
      when: ansible_network_os == 'ios'
      cisco.ios.ios_config:
        src: "ios_ntp.j2"
      notify: ntp_handler_example
      register: ntp_result_ios

    - name: Apply NTP configuration from a template
      when: ansible_network_os == 'junos'
      junipernetworks.junos.junos_config:
        src: "junos_ntp.j2"
        comment: "Updating NTP configuration"
      vars:
        ntp_servers: "{{ hostvars[inventory_hostname].ntp.servers }}"

    - name: "Save Config for IOS"
      when: ansible_network_os == 'ios'
      cisco.ios.ios_command:
        commands: "copy running-config startup-config"

  handlers:
    - name: ntp_handler_example
      debug:
        msg: >
          {% if ansible_network_os == 'ios' %}
            {{ ntp_result_ios }}
          {% elif ansible_network_os == 'junos' %}
            {{ ntp_result_junos }}
          {% endif %}
