---
- name: "VyOS Playbook"
  hosts: vswitch01
  connection: network_cli

  tasks:
    - name: "Remove Push some banner to vyos"
      vyos.vyos.vyos_banner:
        banner: pre-login
        state: absent

    - name: " Add post login banner"
      vyos.vyos.vyos_banner:
        banner: post-login
        text: " Post login banner"
        state: present
